Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/07/2017
Var
perimetro, raio : real


Inicio
 escreva ("Insira o perimetro")
 leia (perimetro)
 escreva ("Insira o raio")
 leia (raio)
 perimetro <- 2*3,14*raio
 escreva (perimetro)


Fimalgoritmo